<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Request for \'{displayName}\' has been approved.' => 'L\'account \'{displayName}\' è stato approvato.',
    'Account Request for \'{displayName}\' has been declined.' => 'L\'account \'{displayName}\' non è stato approvato.',
    'Hello {displayName},<br><br>

   il tuo accont è stato attivato.<br><br>

   Clicca qui per il login:<br>
   <a href=\'{loginURL}\'>{loginURL}</a><br><br>

   Kind Regards<br>
   {AdminName}<br><br>' => '',
    'Ciao {displayName},<br><br>

   la tua richiesta è stata rifiutata.<br><br>

   Kind Regards<br>
   {AdminName}<br><br>' => '',
    'Ciao {displayName},<br><br>
  
   il tuo account è stato attivato.<br><br> 
   
   Clicca qui per il login:<br>
   <a href=\'{loginURL}\'>{loginURL}</a><br><br>
   
   Kind Regards<br>
   {AdminName}<br><br>' => '@@@@',
    'Ciao {displayName},<br><br>
  
   la richiesta del tuo account non è stata approvata.<br><br> 
      
   Kind Regards<br>
   {AdminName}<br><br>' => '@@@@',
    'User not found!' => 'Utente non trovato!',
];
